# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'Keyneez' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Keynee
  pod 'GoogleMLKit/TextRecognition','3.2.0'
  pod 'GoogleMLKit/TextRecognitionKorean', '3.2.0'

  target 'KeyneezTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeyneezUITests' do
    # Pods for testing
  end

end
